### ISSUE TITLE
Delete composer.phar

### ISSUE THREAD

**Issue by taueres** [facile-it/paraunit#10]
The file composer.phar should not be part of the project. It's also quite bit ~1 MB.
I suggest to remote it and add a new .gitignore rule.

**Comment by fntlnz** [comment]
Moreover travis download it at every build so this is definitely not needed in the project vcs.
Is a sin that now it's present in the history, so every clone will be affected by it's size.

**Comment by fntlnz** [comment]
I'm opening a PR to remove this.

**Comment by fntlnz** [comment]
Update: it was intended to be ignored, but it has been added to `.gitignore` before adding it to git.
https://github.com/facile-it/paraunit/blob/master/.gitignore#L6

**Comment by taueres** [comment]
@fntlnz I bet you meant it has been added to .gitignore after adding to git. Isn't it?

**Comment by fntlnz** [comment]
Yes

**Comment by Jean85** [comment]
Fixed by 3d5d6c16, thanks @fntlnz
