### ISSUE TITLE
Default to phpunit.xml

### ISSUE THREAD

**Issue by yisraeldov** [facile-it/paraunit#135]
#14 This should also support `phpunit.xml` instead of only `phpunit.xml.dist`

**Comment by Jean85** [comment]
This seems a straightforward enhancement of this method: https://github.com/facile-it/paraunit/blob/8ec3df7b1c5c0989e299ea2b15214d9cbd324742/src/Paraunit/Configuration/PHPUnitConfig.php#L58-L75

**Comment by Jean85** [comment]
Implemented in #137.

**Comment by yisraeldov** [comment]
Awesome!
