### ISSUE TITLE
Load XML config with default name

### ISSUE THREAD

**Issue by Jean85** [facile-it/paraunit#14]
When using the `--configuration` option, we are forced to specify the file name. We should emulate PHPUnit's behaviour, append the default filename (`phpunit.xml.dist`) if it's not specified.

**Comment by ranpafin** [comment]
I've label it as a bug as well because in the Readme we state:

--configuration as **optional** parameter.

**Comment by Jean85** [comment]
I think that the optional part still works, it loads the `phpunit.xml.dist` in the current working dir.
The problem is that it does so only if the option isn't used.

**Comment by ranpafin** [comment]
Ok so i'm missing the whole point here.
What should be the point of using --configuration if not planning to set a custom file?

**Comment by Jean85** [comment]
I'll explain with an example.. if I have my XML file in the `app` subfolder:

 * with PHPUnit I can do `bin/phpunit -c app`
 * with Paraunit, I'm forced to do `bin/paraunit run -c app/phpunit.xml.dist`
 
I would like to be able to do simply `bin/paraunit run -c app`, as in PHPUnit

**Comment by ranpafin** [comment]
got it, make sense.
