### ISSUE TITLE
--printer flag not respected

### ISSUE THREAD

**Issue by SteveDesmond-ca** [facile-it/paraunit#151]
Steps to reproduce:
1. create a custom printer that does something like outputs the test name after each test result (e.g. `.`/`E`/`F`/etc.)
1. run `vendor/bin/phpunit --printer {printer_class_name}`
1. run `vendor/bin/paraunit --printer={printer_class_name}`

Expected result:
- both `phpunit` and `paraunit` provide similar output

Observed result:
- `paraunit` seems to ignore the `--printer` flag, and displays "default" output

Alternatively, `--testdox` support would handle my use case

**Comment by Jean85** [comment]
Usign `--printer` is not easily doable as of now, I would have to reproduce the whole PHPUnit behavior inside Paraunit; also, that extension point in PHPUnit itself is deprecated and will be removed in PHPUnit 9.

As for testdox, I fear that as of now, Paraunit doesn't collect enough info to print out that format; that would probably require a complete rewrite of the feature on this side too.

**Comment by stevedesmond-ca** [comment]
:+1: Understandable, I think this issue then becomes "remove the `--printer` flag from the CLI help text so as to not imply that this functionality exists/works.`

**Comment by Jean85** [comment]
Closing as this is completely solved in 2.0 thanks to the new event system, and the `--passthrough` option when needed. Won't do anything on 1.x, sorry.
