### ISSUE TITLE
Add support for cobertura

### ISSUE THREAD

**Issue by elernonelma** [facile-it/paraunit#157]
Since release https://github.com/sebastianbergmann/php-code-coverage/blob/master/ChangeLog.md#920---2020-10-02  phpunit is able to generate cobertura report: `phpunit --coverage-cobertura=cobertura.xml`

We use it in our gitlab factory and works fine - do you have any plan to work on it? I may have some time to look at an implementation but not until maybe mid december.

**Comment by Jean85** [comment]
Implementation should be pretty straightforward, since we reuse PHPUnit components to generate coverage. PR appreciated!
