### ISSUE TITLE
Github pages doc

### ISSUE THREAD

**Issue by fntlnz** [facile-it/paraunit#18]
I was wondering if it's not time to build a documentation website for this project.

Something like this would be very nice: https://facebook.github.io/watchman/

**Comment by ranpafin** [comment]
:+1:  I like the idea.

At the moment  we don't have much material to share but it could a reason to add some more.
@Jean85 you may put some reveal.js *stuff* there ;)

**Comment by Jean85** [comment]
Ahah :smile: reveal.js could be a little premature for now, I don't know...

BTW, a site with some documentation attached should be nice... I hope we will have time soon to write that!

**Comment by Jean85** [comment]
This is WIP!! I already published the site at http://facile-it.github.io/paraunit/, I will work on the docs ASAP, trimming down the README.md to the essentials.

**Comment by Jean85** [comment]
Woha I forgot that I've completed this!
