### ISSUE TITLE
Long time consuming functional tests blocking paraunit end

### ISSUE THREAD

**Issue by Algatux** [facile-it/paraunit#22]
Paraunit execution remains blocked waiting for long functional tests that are running at the end.
I'm working on a solution to eliminate the waiting time for these last long tests. 

The idea is to extract the process stack creation into a service that can use some different strategies to "build" the stack.
One strategy (the default one) is the actual strategy, the other one creates an index with the timing of execution of every single test class and builds a stack based on this index.
With this strategy the longer tests will be executed for first, optimizing the execution and eliminating the long final wait time.

I'm thinking to use different adapters (File, db, others ..) to store che "index" and i would use some sort of configuration to drive it. 
I'm thinking about use [dotEnv](https://github.com/vlucas/phpdotenv) for this purpoose (actually i'm using the command)

Can this solution be usefull?

Here is my forked project [development](https://github.com/Algatux/paraunit/tree/development)

**Comment by ranpafin** [comment]
I think it could be an overall improve of the performance.

The extraction/persistence of the execution time, once implemented, it could be used to report slow tests or for some kind of ranking.

**Comment by Algatux** [comment]
What about using for example SqlPriorityQueue as process stack in this case ? 
http://php.net/manual/en/class.splpriorityqueue.php

The only problem I see is the actual use of the hash (console command md5) as array index

**Comment by Jean85** [comment]
The hash is also used to avoid duplicate insertions in the process queue: that's because multiple rules in the XML config file can match a single test file.

Using an hash, we avoid inserting a test file twice, because the array key will be the same; also, in this way we don't need to search inside or sort (with O(n log n) complexity) to find the duplicates, because the collision is immediate.

I don't know if we can implement the same safeguard with the Spl class... But I would love to discard the array if we can ;)

**Comment by Algatux** [comment]
The SqlQueue / Stack structures do not support any key/index. The SplPriorityQueue supports only an integer (that is not unique). But i think that this responsibility must be moved from the array to (in this case) the test file index.

So the index will contain the filename + it's path (or the hash) and the execution time.
The stack than, will be created using an SplPriorityQueue with the process object prioritized bit it's previous execution time. Unknown (for the index) tests, read as fresh new tests and tests that must be retried will be inserted with maximum priority.

**Comment by Jean85** [comment]
I'm not sure about this... You don't know if all the tests in the index have to be run, you still have to filter using the PHPUnit class as it's already doing... In tway, you  will need to jump between 3 data structures: the index, a temporary array map and the SPL queue; does it still remain interesting to use?

**Comment by ranpafin** [comment]
@Algatux actually it's not a bad idea, now we're taking advantage of the array index to enforce uniqueness and most important to move a specific abject from one *stack* to the other. The spl data types may be a lighter implementation rather than the classic array but we still need to come up with a solution for those 2 features. Any idea here?

**Comment by Algatux** [comment]
@ranpafin yes the uniqueness problem is something that must be kept in mind and i should think about it.

I think that the stack should be created starting from the Filter service result array. Just like it's made actually but keeping trace of the insertion of a process using the index (for example with a flag "inserted").

For moving processes from one stack to another remember that the SplQueue extract method removes one process from the stack to insert it in the running one. At each cycle of the runner, all running processes will be extracted and immediately reinserted if not terminated. About the complete ones it's simply an insertion. I think that at "running time" paraunit doesn't need those identifiers". 
Am I losing something ?

**Comment by ranpafin** [comment]
As i see here : 

`SplPriorityQueue::extract — Extracts a node from top of the heap and sift up.`

If the *running* queue contains like  5 processes, after some iteration a process may complete but it's not on the top of the heap, it may be as well in the middle or at the bottom. How do you solve that?

**Comment by Algatux** [comment]
in the runnner run method, inside the while cycle that checks staks emptyness  we do

```php
foreach ($this->processRunning as $process) {
  if ($process->isTerminated()) {
    $this->eventDispatcher->dispatch(
      ProcessEvent::PROCESS_TERMINATED,
      new ProcessEvent($process, array('output_interface' => $outputInterface,))
    );
    // Completed or back to the stack
    $this->markProcessCompleted($process);
  }
  usleep(500);
}
```
the process identifier here is not needed nor used because the running stack must be iterated, it's only used in "markProcessCompleted" to remove that specific process but using the SplStack (a simple FIFO queue, not prioritized there), there is no anymore process to remove

doing a little recap i mean to use SplPriorityQueue for processStack, SplStack/SplQueue for running, and  SplStack/SplQueue for completed (Stack and Queue ar very similar)

I mean somethin like this (please don't look at the nested if else :P)
```php
while (!empty($this->processStack) || !empty($this->processRunning)) {
    if ($process = $this->runProcess($debug)) {
        $this->eventDispatcher->dispatch(ProcessEvent::PROCESS_STARTED, new ProcessEvent($process));
    }
    $process = $this->processRunning->pop(); // or extract
    if ($process->isTerminated()) {
        $this->eventDispatcher->dispatch(
            ProcessEvent::PROCESS_TERMINATED,
            new ProcessEvent($process, array('output_interface' => $outputInterface,))
        );
        // Completed or back to the stack
        if ($process->isToBeRetried()) {
            $this->processStack->push($process,/** MAX PRIORITY **/);
        } else {
            $this->processComplete->push($process);
        }
    }else {
        $this->processRunning->push($process);
    }
    usleep(500);
}
```
I don't know if this the right solution/implementation but i think it can be an improvement removing (if I'm not loosing anything) the associative array

**Comment by ranpafin** [comment]
Make sense. 

Now we should investigate if making a pop and push for each iteration is more costly than scanning an array.

**Comment by Jean85** [comment]
Sorry to see this issue stale too. I would like to find a solution here, but we do not have any current solution for carrying over data about slow tests.
