### ISSUE TITLE
Support for PHPUnit 11

### ISSUE THREAD

**Issue by Chris53897** [facile-it/paraunit#226]
https://packagist.org/packages/phpunit/phpunit was released today.

I did a quick PR just to test if there are any changes nedded.
There are only some. But i do not know how to fix it.

**Comment by Jean85** [comment]
Looking at the changelog, I don't see much changes that could impact Paraunit: https://github.com/sebastianbergmann/phpunit/blob/11.0.0/ChangeLog-11.0.md

Still, your PR has a failing CI, let me take a look...

I have to decide if I want to allow cross-compatibility or release a new major on our side too.
