### ISSUE TITLE
.gitattributes doesn't ignore enough stuff

### ISSUE THREAD

**Issue by garak** [facile-it/paraunit#242]
The following paths seem to be useless for distribution, and should be ignored too:

.github
.php-cs-fixer.dist.php
CHANGELOG*
codecov.yml
docker-compose*
Makefile
phpstan-baseline.neon
psalm*
rector.php

**Comment by kubawerlos** [comment]
I've added in https://github.com/facile-it/paraunit/pull/261 all mentioned above, except changelogs - after 3 "random" checks - Symofny's components, PSR's packages and PHPUnit all have changelogs in dists.
