### ISSUE TITLE
Sqlite database locked exception non parsed for retry

### ISSUE THREAD

**Issue by Algatux** [facile-it/paraunit#26]
Using sqlite as database with parallel functional tests I found this error that is not matched to retry

SQLSTATE[HY000]: General error: 5 database is locked (SQL: insert into "wallets" ("name", "user_id", "updated_at", "created_at") values (test_wallet, 1, 2015-11-25 21:07:38, 2015-11-25 21:07:38))

**Comment by Jean85** [comment]
Sure, obviously different vendor can have different error messages.
It's easy to implement this, I'll write the test ASAP and implement it.

**Comment by Jean85** [comment]
Done with 7bb4d6a40384f00f86c6f2a8a3a208bbaa30d2e6
I'll merge this in 0.5, PR incoming.
