### ISSUE TITLE
Use of deprecate parameter kernel.root_dir

### ISSUE THREAD

**Issue by garak** [facile-it/paraunit#270]
The [ParallelContainerDefinition](https://github.com/facile-it/paraunit/blob/c1dc87ee951693565a4c2033681fd38dd1a77534/src/Configuration/DependencyInjection/ParallelContainerDefinition.php#L47) sets the `kernel.root_dir` parameter, which is deprecated since Symfony 4.2 (and removed in the newer versions).
I can't see any other references to the same parameter in the codebase, so I suppose it can be removed.
If not, it should be replace with the proper `kernel.project_dir` parameter.

**Comment by Jean85** [comment]
Since this is a custom container (and not a standard FrameworkBundle one), I can use whatever parameter I want.

But I think you found an old unused parameter! :smile: We can remove it and see if everything still works
