### ISSUE TITLE
PHP Warnings marked as F

### ISSUE THREAD

**Issue by Algatux** [facile-it/paraunit#28]
I've noticed that php warnings are marked as F but build return code is 0. Why not mark them as W or something similar ?

**Comment by Jean85** [comment]
Can you please post here the plain output of the test using PHPUnit (and not Paraunit?)

**Comment by Algatux** [comment]
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

PHP Warning:  sprintf(): Too few arguments in /var/www/collaboratori2/src/Facile/Cbr/AgendaBundle/Tests/Functional/Controller/CollaboratoreNonProduttivoControllerTest.php on line 53
.
Warning: sprintf(): Too few arguments in /var/www/collaboratori2/src/Facile/Cbr/AgendaBundle/Tests/Functional/Controller/CollaboratoreNonProduttivoControllerTest.php on line 53


Time: 1.05 seconds, Memory: 89.00Mb

OK (1 test, 4 assertions)

**Comment by Jean85** [comment]
Ah understood. The issue is in the parser: the regex tries to identify the test's results, and it catches some capital F within the warnings. I'm not sure if this could be fixed, I'll try to improve the regex.

**Comment by Jean85** [comment]
I did some research, and I found that PHPUnit should [intercepts PHP Errors and warnings](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.errors):

> By default, PHPUnit converts PHP errors, warnings, and notices that are triggered during the execution of a test to an exception. Using these exceptions, you can, for instance, expect a test to trigger a PHP error [...]

I can't reproduce your problem with a test, how are you having it?

**Comment by Algatux** [comment]
```php
sprintf("text %s, %s",'hello');
```

**Comment by Jean85** [comment]
With that, I got this:

```
PHPUnit 5.1.0 by Sebastian Bergmann and contributors.

...E...                                                             7 / 7 (100%)

Time: 86 ms, Memory: 3.50Mb

There was 1 error:

1) Paraunit\Tests\Unit\TestResultsParserTest::testParseAndContinue with data set #3 (Paraunit\Tests\Stub\StubbedParaProcess Object (...), 'PROVA')
sprintf(): Too few arguments

/home/paraunit/projects/src/Paraunit/Tests/Unit/TestResultsParserTest.php:17

FAILURES!
Tests: 7, Assertions: 12, Errors: 1.

```

I thought that PHPUnit 5 could cause the issue, but I got the same output with 4.8...

**Comment by Algatux** [comment]
Is it possible that using a dataprovider implies a change in the output message ?

**Comment by taueres** [comment]
Is the malformed sprintf executed in the dataProvider?

**Comment by Jean85** [comment]
No, I'm doing it in the test. Anyhow, it's the documented behavior. You have the sprintf in a Symfony controller maybe? Maybe Symfony is catching the warning in some way...

**Comment by taueres** [comment]
It looks like PhpUnit does not capture warnings while executing a test provider.
Here is an example: https://gist.github.com/taueres/0bf3c29b70736a9178b9

**Comment by Jean85** [comment]
Closing this as not reproducible. I will try to improve the regex in the future to avoid similar issues.
