### ISSUE TITLE
Use PHPUnit test result logs instead of stdout parsing

### ISSUE THREAD

**Issue by taueres** [facile-it/paraunit#33]
PHPUnit has support for test result logging (more info [here](https://phpunit.de/manual/current/en/logging.html)). Paraunit could use these instead of parsing stdout which may contain garbage data (eg. var_dumps).

**Comment by Jean85** [comment]
Very interesting! The XML may be the more "robust" approach but maybe is a little heavy to parse. JSON is the opposite... I'll think about it!

**Comment by Jean85** [comment]
I'm closing this in favor of #31, I'll post there my findings.
