### ISSUE TITLE
PHP < 5.5 support.

### ISSUE THREAD

**Issue by Jean85** [facile-it/paraunit#4]
Today I've broken the build twice (4d31ec13d68ab930c01289ff87b45372aaac7751 & 2e5b5eeeb86e1d0eb8c6e91daa659c47fe6c33d8) because I was using `[]` instead of `array()` and the `::class` static shortcut for Prophecy.

PHP 5.3 is alread dead, and 5.4 is already on extended support, and it will dead 1 month from now: http://php.net/supported-versions.php

I propose to push the minimum support to 5.5, to encourage the usage of the supported version.

**Comment by ranpafin** [comment]
Shame on you for breaking the build twice!  :smile: 

The way i see it: it make sense to break 5.3 compatibility in this early stage if it brings some real value to the project.

**Comment by fntlnz** [comment]
IMO what @Jean85 is proposing will lead to two key benefits.

- People working at the project can stop worrying about things like, is this feature X supported on 5.3? 
It's not all about new features, BC must be considered too.
- Discourage use of unsupported php versions

**Comment by Jean85** [comment]
We started from 5.3 because PHPUnit 4.7 supports `PHP>=5.3`; this project is actually a PHPUnit "helper", so it made sense.

The most recent version of PHPUnit pushed the support up to `PHP>=5.6`. It's a major step forward, and I think we should either follow it up to the same level, or stay to 5.3, and basically give full compatibility to at least PHPUnit 4.7.

**Comment by ranpafin** [comment]
Following @fntlnz proposal we could improve the *contributing.md*.
A possible addition could be saying that we will consider a feature request **even if**  it breaks 5.3 compatibility.

Moreover, one of the reasons we may consider enforcing 5.3 compatibility is PhpUnit.
- The project is strongly tied to the version of PhpUnit we're currently using and for any 4.x PhpUnit release is to keep 5.3

**Comment by Jean85** [comment]
As I mentioned in #8, I'm thinking about bumping the PHPUnit constraint to >= 4.6. This doesn't bump the PHP version constraint, BTW!

Proposal: 
 * we can follow the PHPUnit support roadmap: any major version (https://github.com/sebastianbergmann/phpunit/wiki/Release-Process#support)

 > MUST be supported for at least one year after the initial stable version (5.0.0) of the next major release series (5.X) is released."

 * We can wait until support for PHPUnit 4.x is dropped, then bump our PHPUnit constraint to >=5, and our PHP version constraint to the adeguate level, >=5.6

What do you think?

**Comment by fntlnz** [comment]
I think that the most important thing is to find s trade-off between
features we need and backward compatibility, for me 4.6 represent a good
choice both because it's a reasonable old version and because does have
features we need as you mentioned in #8

**Comment by ranpafin** [comment]
In this case it make sense to keep the Phpunit version <= 5.x . With this we can have both the feature we need for handling colors and keep the backward compatibility. As @fntlnz remarked, requirements upgrade should be feature driven.

**Comment by Jean85** [comment]
Ok, I've done it in 51acbcad4afc7a484cfec621ebd44967a38fd708.
I've also pushed the minimum stability to stable.
