### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by ranpafin** [facile-it/paraunit#41]
I think it could turn useful to have a _CONTRIBUTING.md_ file.
Nothing fancy just some basic tasks to run before submitting a PR and maybe the general guidelines. 

More so, Paraunit docker container comes packed with all the tools required to follow these rules, particularly (but not only):

- phpcbf
- phpcs

It would be even better to provide a custom version of the of such tools, even a **contributing.sh** with multiple tasks inside. Something that a developer can run before submitting his contribution. 

---
TO DO
- [x] Choose a coding standard (*full PSR2*)
- [x] Sync scrutinizer with the new coding standard
- [x] Add git *pre-commit* hook 
    - [x]  /src directory
   -  [x]  /tests directory (need to fix non camel-case method names)
- [x] Add a CONTRIBUTING.md

**Comment by Jean85** [comment]
That would be nice! Right now I rely on my IDE and on Scrutinizer to check those things.
Basically, I use PSR code style, Symfony standard for service naming, and I prefer spacing present around the `!` operator.

**Comment by ranpafin** [comment]
@Jean85 yep, i've looked into the .scrutinizer file and i think we have a couple of option to help people get along with the project current code-style. I think t

The first would be creating a custom _ruleset.xml_ taking all we can from _PSR2_ that does not trigger a huge scale autofix from **PHPCBF**. Link that file to both the .scrutinizer and to a custom bash script (contributing.sh) something like:

`phpcs -p --standard=/path/to/custom_ruleset.xml --colors src/ `
`phpcbf --standard=/path/to/custom_ruleset.xml --colors src/ `

The other option will be to enforce the current .scrutinizer configured code-style by creating a custom ruleset with only a couples of rules (spacing present around the ! and . operators.). 

I think we should follow the first approach, it may require a bit of work at the beginning but then we can have 3 tools working with a single .xml file.

I've made some digging with the standard PSR2 ruleset of phpcs [ruleset.xml](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PSR2/ruleset.xml) i think we can make it work (aka without triggering an all-around autofix) with only removing 3/4 rules.

**Comment by Jean85** [comment]
Good!
What rules we need to remove? Are we violating PSR-2 in some way? I would prefer not to!
I would likely ignore just the line-length warnings, even the PSR says that is a soft-limit.

**Comment by fntlnz** [comment]
If you are wondering about a `CONTRIBUTING.md` file I'd suggest you to look also at  ISSUES/PR templates. Take a look at what docker/docker did there: https://github.com/docker/docker/tree/master/.github

**Comment by Jean85** [comment]
I see @fntlnz , but we don't have enough traffic to warrant a template like those, at least not for issues... What are you suggesting we should add?

**Comment by fntlnz** [comment]
I was just pointing out that some projects integrates the CONTRIBUTING.md
file with these templates.

**Comment by ranpafin** [comment]
@Jean85 sure, i'll create a branch so we can all look into.

**Comment by Jean85** [comment]
I've launched the script, and the main result is, apart from some minor fixes that I like, a bunch of `!` operators that are no more spaced.

PSR-2 and Symfony follow the no-space convention, I'm unsure about how to proceed. Should we align Paraunit to this standard? Or should we stay with the spaces?

I'm not sure on how to enforce the spacing, in the latter case..

**Comment by ranpafin** [comment]
I'm more inclined to remove the space altogether and bring the project closer to the PSR-2 standard.

I think it should be the goal of this branch to set a definitive code style guide so, even if there will be some changes (like the one above) it could make sense to proceed.

**Comment by Jean85** [comment]
Agreed. This should also mean that the spacing around the concatenation operator should be removed, and spacing should be present after a casting operator.

This should generate a bit of corrections, but it's better do it now and stick with some fixed and well shared rules as PSR are.

**Comment by Jean85** [comment]
Ok, I've pushed the proposed fixes. Next and last step should be a post-commit git hook to impose the standard.

**Comment by ranpafin** [comment]
Hook is ready, it will be created at the first "composer install" command. 

We still need a CONTRIBUTING.md then i think we're good.

**Comment by Jean85** [comment]
Shouldn't we suppress the output to avoid spamming the console when committing?

**Comment by ranpafin** [comment]
@Jean85 i've changed the logic a bit, rather than forcing an autofix now it will only run *phpcs* and leave the code review job to the developer.

Also if *phpcs* fails (exit code != 0) the commit will be blocked and the user will see the the reason in the output. It's an hard limit i'm not sure if it's the right way.

Run composer install again to get the updated version of the hook and let me know what you think.

*NOTE: i've lowered the severity on warning so we ignore the line limit*

**Comment by Jean85** [comment]
The Git hooks can always be avoided with `git commit --no-verify`, so it's not an hard limit ;)
I've seen your changes, LGTM.
You would add a `--force` or `--autofix` option to the script BTW, to force the changes.

**Comment by Jean85** [comment]
Ok I took a stab at the .md file: https://github.com/facile-it/paraunit/blob/2203_contributing/CONTRIBUTING.md

Please review it!

**Comment by ranpafin** [comment]
LGTM, i've mentioned docker at the beginning with a link to the installation process.

**Comment by Jean85** [comment]
Good! :+1: 
Ok, I've fixed and included the tests in the check. I'll open a PR for this branch to discuss and review it further
