### ISSUE TITLE
Docker PHP enviroment

### ISSUE THREAD

**Issue by ranpafin** [facile-it/paraunit#42]
It would be nice to compile PHP from source (using one of the official PHP docker images) rather than relaying to  Debian's repository.

This would give us the ability to easily create 2 docker images: 
 - PHP 7.x (FROM php:7/7-cli)
 - PHP 5.6.x (FROM php:5.6/5.6-cli)

and also keep the container cleaner.

what do you think?

**Comment by Jean85** [comment]
That would be nice, but we should evaluate if the build time for the container would increase or decrease. We do not have a Docker image right now, and launching the container means a rebuild if you haven't it in the cache.

We should try and see! I have an other image built from PHP7-fpm that I use for work, I could try and start from that!

**Comment by ranpafin** [comment]
Closed with PR #43
