### ISSUE TITLE
Phar Archive

### ISSUE THREAD

**Issue by fntlnz** [facile-it/paraunit#5]
I think that we should distribute paraunit as a phar archive in order to allow users to simply wget it from our site and than use it without the need of anything else than php

**Comment by Jean85** [comment]
The project itself has some vital dependencies:

 *   symfony/console
 *   symfony/dependency-injection
 *   symfony/config
 *   symfony/process
 *   phpunit/phpunit

Packing it in a phar doesn't create a problem about it? It's not a fully indipendent piece of code, at least not right now...

**Comment by ranpafin** [comment]
@fntlnz it could be an alternative to the composer installation. I think it's doable.

@Jean85 We'll need to pack all the the dependency as well to make it work.

**Comment by fntlnz** [comment]
@Jean85 It should not create any problems. A lot of big projects with a lot of dependencies do it.

PHPUnit itself does, see [there](https://github.com/sebastianbergmann/phpunit/tree/master/build)

**Comment by taueres** [comment]
I think the best solution is to add a build system. Phing is the tool adopted by Phpunit.

**Comment by taueres** [comment]
We should also clean up the Paraunit starting command. IMHO `./bin/paraunit [OPTIONS]` without "run" is easiest.

**Comment by Jean85** [comment]
@taueres that is possible only through a .sh file. the `run` part is the name of the command, required by the `symfony/console` Command component.

**Comment by taueres** [comment]
I've implemented Phar standalone executable on branch [phar_archive](https://github.com/facile-it/paraunit/compare/phar_archive).
You can download the archive [here](http://s000.tinyupload.com/index.php?file_id=45296105998421967268) or you can build your own: just execute `./paraunit/docker/build-phar.sh` and it will create the Phar to `./paraunit/phar/paraunit.phar`.

I've run Symfony Routing tests with the Phar archive and it seems to work really well.

Is there any room for further improvements?

**Comment by Jean85** [comment]
Great work! Thanks!
I don't think there is anything to improve in the PHAR. It's also great that you created a script that does all that we need to build the PHAR in the container!

We should discuss where to host it, anyhow.
I was thinking to use the GitHub release feature: https://github.com/facile-it/paraunit/releases
Any other suggestions?

**Comment by ranpafin** [comment]
Nice Job! I was looking forward to see this  :+1: 

Releases binary attachment seems the way to go, phpunit usually adopt an external *"repository"* but i see not reason to separate the archive from the actual release.

When there will be a dedicated website we could link the .phar there as well.

**Comment by taueres** [comment]
Atm the PHAR archive must have execution permissions to work properly.
That is because the Paraunit subprocesses (PHPUnit runners) actually execute the PHAR itself with a special parameter.

**Comment by Jean85** [comment]
And launching the PHAR itself doesn't need the permission too?

> When there will be a dedicated website we could link the .phar there as well.

The site is already there :joy_cat: http://facile-it.github.io/paraunit

**Comment by taueres** [comment]
Yep that's exactly what I ment. Subprocess won't work without exec permission even if you can run the main thread with `php paraunit.phar`.

**Comment by Jean85** [comment]
Ok! That should be mentioned in the documentations, I hope I will not forget to add that!
Can you open a PR, so we can review the code and merge it?

**Comment by taueres** [comment]
Here it is: https://github.com/facile-it/paraunit/pull/45

**Comment by Jean85** [comment]
Oh I forgot to close this! Today I released the second PHAR using #62, so we can say it's working!
