### ISSUE TITLE
Make logo printer optional or configurable

### ISSUE THREAD

**Issue by Jean85** [facile-it/paraunit#55]
I would like to make the shark logo optional or configurable with the stable release. It was nice for the unstable, but I think it may look "personalized" for a software that we like to distribute.

**Comment by ranpafin** [comment]
@Jean85 agree on this one, the logo could be displayed with a command line argument  something like:

```bash
--display-logo', '--show-logo'

```

**Comment by Jean85** [comment]
I didn't think about it, yeah! That may be the easy to do, maybe I can inject the behavior once I merge #11

**Comment by Jean85** [comment]
Done! See 56a82041834b1927016e2c96dd14ba6faff6713c
