### ISSUE TITLE
Too much disk space occupied

### ISSUE THREAD

**Issue by Jean85** [facile-it/paraunit#63]
Yesterday I tried launching the coverage command over a very large codebase. The execution failed due to not having space to save the logs and the coverage results. We should delete the logs and the files right after reading them, to save on space while executing the tests.

**Comment by taueres** [comment]
Wow! I think we might also have some memory issues while merging the files together. That's interesting, keep us updated! :-D

**Comment by Jean85** [comment]
Well, normally I use `/dev/shm` for those files, so it was competing for the same resource (RAM).
Merging shouldn't be an issue after I fix this issue, since the operation itself makes a lot of stuff collapse over the same mega-array.

If I clean up the files, I should save a lot of memory, freeing it for the merged result inside the Paraunit main process.
