### ISSUE TITLE
Abstract test cases should not be executed

### ISSUE THREAD

**Issue by sergeyz** [facile-it/paraunit#64]
Looks like we should skip abstract classes in the test folder.

Few examples in Symfony
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Tests/Validator/AbstractTest.php
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Tests/AbstractFormTest.php

```
Abnormal Terminations (fatal Errors, Segfaults) output:
1) UNKNOWN -- log not found
Abnormal termination -- complete test output:
Class '/home/travis/build/laboro/dev/package/platform/src/Oro/Bundle/TranslationBundle/Tests/Functional/ImportExport/Strategy/AbstractTranslationImportStrategyTest' could not be found in '/home/travis/build/laboro/dev/package/platform/src/Oro/Bundle/TranslationBundle/Tests/Functional/ImportExport/Strategy/AbstractTranslationImportStrategyTest.php'.
```

**Comment by Jean85** [comment]
I've already encountered this issue.
Right now, the main issue is that I don't read inside the test files like PHPUnit does, so I'm not able to discern abstract from non-abstract classes. I solved this issue before with a naming convention, making abstract classes not caught up by the prefix/suffix settings of PHPUnit.

I'm open to suggestions; if anyone has an approach to avoid those problems, I'm all ears!

**Comment by sergeyz** [comment]
We follow Symfony convention too.

```
Prefix abstract classes with Abstract. Please note some early Symfony classes do not follow this convention and have not been renamed for backward compatibility reasons. However all new abstract classes must follow this naming convention;
```

I think it's ok to make this prefix default

**Comment by Jean85** [comment]
Then, you can hotfix this changing the XML config, blacklisting the tests that have this prefix, right?
I'm not sure if blacklisting by default in Paraunit is a good idea, I can't assume that that convention is always used; as an example, I have a `AbstractEntityTest.php` in a project of mine, but the test is not abstract, the tested class is (well, the tested features, through child classes).

**Comment by sergeyz** [comment]
Ok, but let's leave this issue open, just not to forget to skip abstract test suites somehow (check using AST maybe?)

**Comment by Jean85** [comment]
I don't know how to do that, and I'm from mobile so my Google-fu is somewhat limited right now..but definitely yes, I don't want to close this issue. 

I would like to remove abstract test classes from the execution queue beforehand, but only if that is possible without impacting too much on performances. Otherwise, I would prefer an other approach, just catching those cases afterwards, while analyzing the test outcome. I need to investigate what outcome I get via logs and exit code when I wrongly try to execute PHPUnit over an abstract test class.

**Comment by sergeyz** [comment]
Just rename them to *TestCase

**Comment by yisraeldov** [comment]
@Jean85 

This could just take avanage of phpunit's parsing.

`phpunit --list-tests` 

That will give you all the runable tests.

**Comment by Jean85** [comment]
Thanks @yisraeldov but unfortunately that outputs the FQCN, which is no use for Paraunit: I cannot launch tests from the class name, I need the file name...

**Comment by dxops** [comment]
@Jean85 https://blog.wyrihaximus.net/2016/10/utilizing-composers-classloader-to-get-a-class-contents/

**Comment by Jean85** [comment]
That unfortunately iwouldn't always work. PHPUnit works event with classes that have broken the PSR-0/4 autoloader, or even files that do not contains classes, like the PHPT tests. That would not work with that approach.

OTOH, it would be possible to parse that output anyway and act on it, but I fear that it would be slow...
