### ISSUE TITLE
Add Hook and lifecycle logic

### ISSUE THREAD

**Issue by ranpafin** [facile-it/paraunit#7]
@Jean85  With commit 9d4bf8e7ac76092f740ad80f26216dcfcbe13498 we can now add a lifecycle logic to the runner.

With this little upgrade it will be easier to add any new behavior such:

- Something that need to be executed before the process is started (eg. Event: **process.before_start** and **process.start**).
- Something that need to be executed when the engine complete his work  (eg. Event: **engine.end**).

At the present time we only have **engine.before_start** which is hooked to the output formatter and shark printer but the infrastructure is there!

My proposal is to move some dependency away from the runner so it will be easier to unit test.
As a side note, using events in key areas will improve the system extensibility.

**Comment by Jean85** [comment]
Nice!

**Comment by ranpafin** [comment]
Supported events are now:

* **engine.before_start** ( listen by SharkPrinter)
* **engine.start** ( nothing atm )
* **engine.end** ( listen by FinalPrinter)
* **process.started** ( nothing atm)
* **process.terminated** ( listen by  RetryManager, ProcessOutputPrinter)

The runner lost most of his dependency and feel more clean.

**Comment by Jean85** [comment]
All done in 21c55b70ddf6e896b163a5a573e8514ae3b71ad9 right? Good!
I think I will use `process.terminated` in #11

**Comment by Jean85** [comment]
Should we release this with 0.5?

**Comment by Jean85** [comment]
I had to fix the listeners priority: c26e7870c45339c133a7e44f832ee746f0108877

**Comment by ranpafin** [comment]
Yes i can see that. Good catch!

 It's a shame we had to put a priority for events... I'll look into making those methods commutative.

**Comment by Jean85** [comment]
The priority was the quick fix.
Maybe we can change the behaviour a little, with the printer triggered by the parser in some way (directly? with a new event?)
Also, the parser is not required if the retry is needed. Do you think it'll be a good idea to take the RetryManager and convert it to a parser? It will become the first of the chain...

**Comment by ranpafin** [comment]
Yes i think it would make sense moving it to the perser list, at the moment the retry parser feels kinda void...
We could merge those 2 and give more purpose to the current parser.

**Comment by Jean85** [comment]
Ok, I've open a new issue ( #21 ) for the refactoring, I'm closing this, it's all done for now, we can use the events as they are.
