### ISSUE TITLE
Add phpdbg check to builds

### ISSUE THREAD

**Issue by sergeyz** [facile-it/paraunit#76]
Works much faster, on big codebase it's better to use phpdbg instead of xdebug

```
phpdbg -qrr bin/phpunit --testsuite=unit  --coverage-text
```

**Comment by Jean85** [comment]
It's already supported! The only thing that you have to do is have the PHPDBG binary available in your environment, and disable xdebug (to avoid excessive memory consumption).

I've already amended the docs to mention this: http://engineering.facile.it/paraunit/documentation/#coverage-command

**Comment by sergeyz** [comment]
Thanks, I saw it right after issue created. Should we use it on travis?

**Comment by Jean85** [comment]
Do you mean to collect coverage for your own project? Or for Paraunit itself?

**Comment by sergeyz** [comment]
Both ways should be checked continuously

**Comment by Jean85** [comment]
With Paraunit it's checked at startup, and it writes it too after the title; in Travis, I think I will add it, if PHPDBG is present or it's fast to install.

**Comment by Jean85** [comment]
I've tried to add it on Travis and failed, PHPDBG is not present there, due to travis-ci/travis-ci/issues/6323

**Comment by sergeyz** [comment]
We can use it for php7 only. The main goal is to make sure it works

**Comment by Jean85** [comment]
It's not there, no matter PHP version. So:

 * I cannot use it to collect Paraunit's coverage, until the referred issue is solved on Travis
 * I don't have a test that uses PHPDBG directly to test the collection of the coverage: I shouldn't test if the PHPDBG coverage driver works, that's on php-code-coverage's testsuite
