### ISSUE TITLE
Block PHPUnit colors in CLI instead of requiring to disable it in XML config

### ISSUE THREAD

**Issue by Jean85** [facile-it/paraunit#8]
I've just discovered that you can disable PHPUnit colors in CLI with:

`--colors=never`

I would like to enforce it on every PHPUnit process that Paraunit launches, to avoid parsing problems and to remove from requirements the disable of colors from the XML config file.

BTW, I need first to investigate from which version of PHPUnit this option is supported... I think I'll open an issue on PHPUnit because this option is undocumented.

**Comment by Jean85** [comment]
Ok, I've discovered that this CLI feature is present from PHPUnit 4.6.0: https://github.com/sebastianbergmann/phpunit/pull/1527

This Paraunit fix then will bring up the requirements to that version. I think it will be fair, since the minor versions of PHPUnit shouldn't have BC problems, and they're dropped from support immediately when a newer minor is released.

**Comment by ranpafin** [comment]
@Jean85 As a side note i noticed a few posts of Bergman in which he remarked some sort of 'project policy' to keep command line argument to a minimum. The idea was to move everything (that can be moved) to the .xml config file.

This feature seem to contradict such policy but i wouldn’t count too much much on his lifespan :)

**Comment by Jean85** [comment]
I saw that too, but it was in a previous pull request. But this feature is an extension of the `--colors` option, that is present since 3.0, I think. So, it's safe to assume that's here to stay ;)
