### ISSUE TITLE
Show FQCN in result output

### ISSUE THREAD

**Issue by sergeyz** [facile-it/paraunit#80]
```
7 files with SKIPPED OUTCOME:
 PdoMysqlTest.php
 IntegrationControllerTest.php
 AttributeFamilyControllerTest.php
 EmailActivitySuggestionControllerTest.php
 EmailActivitySearchControllerTest.php
 GetRestJsonApiWithRenamedFieldsTest.php
 ActivityListRoleControllerTest.php
```

On large codebase it's not so useful, so would be great to see namespace here

**Comment by Jean85** [comment]
I agree, I've noticed this on some cases in my usage of Paraunit too.

Unfortunately, I don't have the FQCN of the tests, just the path. Do you thing it's enough?

**Comment by Jean85** [comment]
Using the ClassLoader may not work with the PHAR, since the autoloader used
by Paraunit inside the PHAR will be different from the one of the test
suites...

Il ven 30 dic 2016, 11:34 Sergey Zhuravel <notifications@github.com> ha
scritto:

**Comment by Jean85** [comment]
I'm currently working on #74, implementing the support for the Teamcity log format.
That log format reports the FQCN of the test class, so it may solve this issue pretty nicely.

**Comment by Jean85** [comment]
Done! I will release this in the upcoming 0.8 release

**Comment by sergeyz** [comment]
@Jean85 Thanks!
