### ISSUE TITLE
Test file path should are relative to .xml config file path

### ISSUE THREAD

**Issue by Jean85** [facile-it/paraunit#9]
I was trying to use Paraunit in a project where the .xml config file isn't in the root dir of the project itself.

This causes an issue: the test suites are defined with relative paths, but they are relative to the config file position. This must be fixed.

When the  `--configuration` parameter is passed to paraunit, the filename should be stripped from the value, and the remaining is to be prepended to every file test path when launching the PHPUnit processes.

**Comment by taueres** [comment]
That's right. Can you please provide a link for a project that uses this kind of configuration? It will be useful for testing.

**Comment by Jean85** [comment]
I don't have one right away, I'm trying to do it on "our" private project ;)
I think I have a fast way to fix it, in the `Filter` class. I'm working on it right now.

**Comment by Jean85** [comment]
Fixed with 4cf3ac585592ead5e52b9bfa0d86bc01f508220f

**Comment by Jean85** [comment]
I think I've not fixed it correctly. The `File_Iterator_Facade` from PHPUnit wants the path absolutes to start with, or it will not resolve the wildcards.

Fix coming ASAP.

**Comment by Jean85** [comment]
Ok, now it's really fixed. I've also polished the paths here and there with `realpath`
